### ISSUE TITLE
Shortcut command  for window not working

### ISSUE THREAD

**Issue by Harfho** [KarimPwnz/firefox-new-container-tab#4]
The ctrl+shift+, (comma) is not working.

**Comment by KarimPwnz** [comment]
Hey,

Thanks for opening this issue!

You can check what shortcut the extension occupies by 
1. Going to `about:addons` on Firefox
2. Opening "Manage Extension Shortcuts" 
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/14217083/131382205-62b68766-0777-4142-984b-836a7f6ea49c.png">
3. Finding New Container Tab
<img width="719" alt="image" src="https://user-images.githubusercontent.com/14217083/131382259-690b8451-9523-48c1-8b8b-5bc15756a21e.png">

Do tell me what you see.

**Comment by Harfho** [comment]
But it’s not working

**Comment by Harfho** [comment]
Ok , gotten it now , u have to pin the extension to make the shortcut work
