### ISSUE TITLE
Impovement request: Customizable hot key

### ISSUE THREAD

**Issue by GCRaistlin** [KarimPwnz/firefox-new-container-tab#5]
Ctrl-Shift-comma is hard to press with the left hand only (the right one is on the mouse). Can you please make it customizable? Or at least add an alternative like Ctrl-Alt-C.

**Comment by KarimPwnz** [comment]
Hey,

Thank you for opening this issue; really appreciate it!

I believe Firefox allows you to change the hotkeys for an extension. As per our README:
> You can always change default shortcuts at about:addons > Settings (gear icon) > Manage Extension Shortcuts

Did you give that a try?

Thanks!

**Comment by GCRaistlin** [comment]
I didn't know about that. Thanks, it's working.

**Comment by KarimPwnz** [comment]
Yay! Glad to hear that worked. Enjoy the extension!
