### ISSUE TITLE
Make the keyboard shortcut work regardless of the active keyboard layout

### ISSUE THREAD

**Issue by GCRaistlin** [KarimPwnz/firefox-new-container-tab#7]
Currently, the keyboard shortcut (I've customized it to Ctrl-Alt-C) doesn't work if the current keyboard layout isn't English. In my case, it doesn't work when the current keyboard layout is Russian. Please make the keyboard shortcut in your add-on keyboard layout independent.
It should be possible as I have at least one another add-on installed which keyboard shortcut works both with English and Russian keyboard layout active (New Container Tab, Alt-C).

**Comment by KarimPwnz** [comment]
(Resolved in #5)
