### ISSUE TITLE
Feature request: set default container for new tab/window

### ISSUE THREAD

**Issue by angelod1as** [KarimPwnz/firefox-new-container-tab#8]
This is slightly like #6 but with a different suggestion:

Create a new setting in which the user can set a default container. Any new tab opened traditionally, or new window, would automatically be open in that set container. If you purposefully open a tab in a new container of course this would not be triggered.

I could try to implement something but I've never touched any browser extensions in my life (but, afaik, it's JS). I'd just like to know if PRs are appreciated and if you think this is feasible.

Thanks.

**Comment by KarimPwnz** [comment]
Hey,

Apologies for the late response—this somehow slipped through. I believe in the case of this extension, functionality drives design, and the functionality is intentionally limited. This extension serves one purpose: to add a popup that allows you to specify containers for new tabs, nothing more.

I am not sure if an extension already exists for what you want. If not, I encourage you to build it yourself using the [contextualIdentities API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contextualIdentities). You can also take inspiration from the [Temporary Containers](https://github.com/stoically/temporary-containers) extension—its functionality is adjacent to what you want.

In any case, let me know if you end up creating such an extension—that would be cool! And do submit other issues/PRs if need be.

Thank you for your time <3
